export const CREATE_QUESTION_PAGE = "CREATE_QUESTION_PAGE";
export const LIST_QUESTION_PAGE = "LIST_QUESTION_PAGE";
export const TEST_PAGE = "TEST_PAGE";
export const WORKOUT_PAGE = "WORKOUT_PAGE";
export const EXERCISES_PAGE = "EXERCISES_PAGE";
export const ROUTINES_PAGE = "ROUTINES_PAGE";
export const PROGRESS_PAGE = "PROGRESS_PAGE";